import React from "react";
import { FaEnvelope, FaPhone, FaMapMarkerAlt } from "react-icons/fa";

const PrivacyPolicy = () => {
  return (
    <div className="container mx-auto p-4 border-2 rounded-xl py-5 my-5">
      <h1 className="text-xl font-semibold mb-4">Privacy Policy</h1>
      <hr className="border-t border-gray-300 mb-5" />

      <p className="mb-4 text-xs">
        At Sigma Solutions, our priority is to protect your private and
        sensitive information gathered from you through the Sigma Solutions
        website or any other plug-ins exchanging information with Sigma
        Solutions Applications. Sigma Solutions takes your privacy very
        seriously and has formed this privacy policy and internal
        policies/practices to keep your personal and financial information safe
        and secure. The Privacy Policy covers our actions regarding the personal
        information we collect when you use online services through our website
        platform. By using the Services, you consent to the practices described
        in the Terms of Use as well as our Terms of Service. By using Sigma
        Solutions Online Services, you accept the terms of this Privacy Policy.
      </p>
      <p className="mb-4  text-xs">
        The terms "We" / "Us" / "Our" / "Company" / "Sigma Solutions"
        individually and collectively refer to Sigma Solutions, and the terms
        "You" / "Your" / "Yourself" refer to the users.
      </p>
      <p className="mb-4  text-xs">
        This Privacy Policy is an electronic record in the form of an electronic
        contract formed under the Information Technology Act, 2000 and the rules
        made thereunder, including amended provisions pertaining to electronic
        documents/records in various statutes as amended by the Information
        Technology Act, 2000. This Privacy Policy does not require any physical,
        electronic, or digital signature.
      </p>
      <p className="mb-4  text-xs">
        This Privacy Policy is a legally binding document between you and Sigma
        Solutions. The terms of this Privacy Policy will be effective upon your
        acceptance of the same (directly or indirectly in electronic form, by
        clicking on the “I accept” tab or by use of the website or by other
        means) and will govern the relationship between you and Sigma Solutions
        for your use of the website “www.sigmasolutions.in” (defined below).
      </p>
      <p className="mb-4  text-xs">
        This document is published and shall be construed in accordance with the
        provisions of the Information Technology (Reasonable Security Practices
        and Procedures and Sensitive Personal Data of Information) Rules, 2011
        under the Information Technology Act, 2000; that require publishing of
        the Privacy Policy for collection, use, storage, and transfer of
        sensitive personal data or information.
      </p>
      <p className="mb-4  text-xs">
        Please read this Privacy Policy carefully. By using the Website, you
        indicate that you understand, agree, and consent to this Privacy Policy.
        If you do not agree with the terms of this Privacy Policy, please do not
        use this Website.
      </p>
      <p className="mb-4  text-xs">
        By providing us with your information or by making use of the facilities
        provided by the Website, you hereby consent to the collection, storage,
        processing, and transfer of any or all of your personal and non-personal
        information by us as specified under this Privacy Policy. You further
        agree that such collection, use, storage, and transfer of your
        information shall not cause any loss or wrongful gain to you or any
        other person.
      </p>

      <h2 className="text-md font-semibold mb-2">SCOPE</h2>
      <hr className="border-t border-gray-300 mb-5" />

      <p className="mb-4  text-xs">
        This policy is applicable to{" "}
        <a
          href="http://www.sigmasolutions.in/"
          className="text-blue-600 hover:underline"
        >
          http://www.sigmasolutions.in/
        </a>{" "}
        and any other websites and services that are displayed or linked to this
        statement and are owned, operated, and managed by the management of
        Sigma Solutions.
      </p>

      <h2 className="text-md font-semibold mb-2">GENERAL</h2>
      <hr className="border-t border-gray-300 mb-5" />

      <p className="mb-4  text-xs">
        a) This document is an electronic record in terms of the Information
        Technology Act, 2000 and rules thereunder, as applicable, and the
        amended provisions pertaining to electronic records in various statutes
        as amended by the Information Technology Act, 2000. This electronic
        record is generated by a computer system and does not require any
        physical or digital signatures.
      </p>
      <p className="mb-4  text-xs">
        b) This document is published in accordance with the provisions of Rule
        3 (1) of the Information Technology (Intermediaries Guidelines) Rules,
        2011, that require publishing the rules and regulations, privacy policy,
        and Terms of Use for access or usage of sigmasolutions.com.
      </p>
      <p className="mb-4  text-xs">
        c) The domain name{" "}
        <a
          href="http://www.sigmasolutions.in/"
          className="text-blue-600 hover:underline"
        >
          http://www.sigmasolutions.in/
        </a>{" "}
        ("Website") is owned and operated by Sigma Solutions, a Private Company
        limited by shares, incorporated under the provisions of the Companies
        Act, 2013, and having its registered office at [Company Address], where
        such expression shall, unless repugnant to the context thereof, be
        deemed to include its respective representatives, administrators,
        employees, directors, officers, agents, and their successors and
        assigns.
      </p>
      <p className="mb-4  text-xs">
        d) For the purpose of this Privacy Policy ("Policy"), wherever the
        context so requires:
        <ul className="list-disc ml-6  ">
          <li>
            i) The term 'You' & 'User' shall mean any legal person or entity
            accessing or using the services provided on this Website, who is
            competent to enter into binding contracts as per the provisions of
            the Indian Contract Act, 1872.
          </li>
          <li>
            ii) The terms 'We', 'Us', & 'Our' shall mean the Website and/or the
            Company, as the context so requires.
          </li>
          <li>
            iii) The terms 'Party' & 'Parties' shall respectively be used to
            refer to the User and the Company individually and collectively, as
            the context so requires.
          </li>
        </ul>
      </p>
      <p className="mb-4  text-xs">
        e) The headings of each section in this Policy are only for the purpose
        of organizing the various provisions under this Policy in an orderly
        manner and shall not be used by either Party to interpret the provisions
        contained herein in any manner. Further, it is specifically agreed to by
        the Parties that the headings shall have no legal or contractual value.
      </p>
      <p className="mb-4  text-xs">
        f) The use of the Website by the User is solely governed by this Policy
        as well as the Terms of Use of the Website ("Terms", available at{" "}
        <a
          href="http://www.sigmasolutions.in/"
          className="text-blue-600 hover:underline"
        >
          http://www.sigmasolutions.in/
        </a>
        ), and any modifications or amendments made thereto by the Company from
        time to time, at its sole discretion. Visiting the home page of the
        Website and/or using any of the services provided on the Website shall
        be deemed to signify the User’s unequivocal acceptance of this Policy
        and the aforementioned Terms, and the User expressly agrees to be bound
        by the same. The User expressly agrees and acknowledges that the Terms
        and Policy are co-terminus, and that expiry/termination of either one
        will lead to the termination of the other.
      </p>
      <p className="mb-4  text-xs">
        g) The User unequivocally agrees that this Policy and the aforementioned
        Terms constitute a legally binding agreement between the User and the
        Company and that the User shall be subject to the rules, guidelines,
        policies, terms, and conditions applicable to any service that is
        provided by the Website. These shall be deemed to be incorporated into
        the Terms and shall be treated as part and parcel of the same. The User
        acknowledges and agrees that no signature or express act is required to
        make these Terms and the Policy binding on the User, and that the User’s
        act of visiting any part of the Website constitutes the User’s full and
        final acceptance of the Policy and the aforementioned Terms.
      </p>
      <p className="mb-4  text-xs">
        h) The Parties expressly agree that the Company retains the sole and
        exclusive right to amend or modify the Policy and the aforementioned
        Terms without any prior permission or intimation to the User. The User
        expressly agrees that any such amendments or modifications shall come
        into effect immediately. The User has a duty to periodically check the
        Policy and Terms and stay updated on their provisions and requirements.
        If the User continues to use the Website following such a change, the
        User will be deemed to have consented to any and all
        amendments/modifications made to the Policy and Terms. In so far as the
        User complies with the Policy and Terms, he/she is granted a personal,
        non-exclusive, non-transferable, revocable, limited privilege to enter,
        access, and use the Website.
      </p>

      <h2 className="text-md font-semibold mb-2">COLLECTION OF INFORMATION</h2>
      <hr className="border-t border-gray-300 mb-5" />

      <p className="mb-4  text-xs">
        Once you visit our website or purchase services from us, we may collect
        personally identifiable information, such as your name, email address,
        mobile number, etc. While providing services, we may register your
        business and create a login ID and password on your behalf and keep that
        for such delivery of services. For filing returns and other related
        services, we may ask for your login credentials to deliver such
        services. For preparing accounts, balance sheets, and filing returns, we
        may take your business details along with its bank statements. For your
        security, we do not retain your sensitive data.
      </p>

      <h2 className="text-md font-semibold mb-2">
        USE OF INFORMATION COLLECTED
      </h2>
      <hr className="border-t border-gray-300 mb-5" />

      <p className="mb-4  text-xs">
        We use the information that we collect to provide, maintain, and improve
        our services, and to protect our users. We may use your personal
        information to:
        <ul className="list-disc ml-6">
          <li>i) Provide, maintain, and improve our services.</li>
          <li>ii) Notify you about changes to our services.</li>
          <li>
            iii) Allow you to participate in interactive features of our
            services when you choose to do so.
          </li>
          <li>iv) Provide customer support.</li>
          <li>
            v) Gather analysis or valuable information so that we can improve
            our services.
          </li>
          <li>vi) Monitor the usage of our services.</li>
          <li>vii) Detect, prevent, and address technical issues.</li>
          <li>viii) Fulfill any other purpose for which you provide it.</li>
        </ul>
      </p>

      <h2 className="text-md font-semibold mb-2">
        SECURITY OF YOUR INFORMATION
      </h2>
      <hr className="border-t border-gray-300 mb-5" />

      <p className="mb-4  text-xs">
        The security of your personal information is important to us, but
        remember that no method of transmission over the Internet, or method of
        electronic storage, is 100% secure. While we strive to use commercially
        acceptable means to protect your personal information, we cannot
        guarantee its absolute security. However, we have implemented reasonable
        security practices and procedures in accordance with the applicable laws
        and standards to protect your personal information.
      </p>

      <h2 className="text-md font-semibold mb-2">
        CHANGES TO THIS PRIVACY POLICY
      </h2>
      <p className="mb-4  text-xs">
        We may update our Privacy Policy from time to time. We will notify you
        of any changes by posting the new Privacy Policy on this page. You are
        advised to review this Privacy Policy periodically for any changes.
        Changes to this Privacy Policy are effective when they are posted on
        this page.
      </p>

      <div className="my-8 p-4 bg-gray-100 rounded-lg shadow-md dark:bg-neutral-800">
        <h2 className="text-md font-semibold mb-4 text-center text-green-500">
          CONTACT US
        </h2>
        <p className="mb-4 text-center text-xs">
          If you have any questions about this Privacy Policy, please contact
          us:
        </p>
        <div className="flex flex-col items-center text-xs">
          <div className="flex items-center mb-2">
            <FaEnvelope className="text-green-500 mr-2" />
            <a
              href="mailto:support@sigmasolutions.in"
              className="text-gray-800 hover:text-green-500 dark:text-white"
            >
              support@sigmasolutions.in
            </a>
          </div>
          <div className="flex items-center mb-2">
            <FaPhone className="text-green-500 mr-2" />
            <span className="text-gray-800 hover:text-green-500 dark:text-white">
              +1234567890
            </span>
          </div>
          <div className="flex items-center">
            <FaMapMarkerAlt className="text-green-500 mr-2" />
            <span className="text-gray-800 dark:text-white">
              [Company Address]
            </span>
          </div>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
